In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel("Book1.xlsx")
print(df)

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78
3     104  Sneha   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [6]:
print(df.head(3))

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78

In [7]:
print(df.tail(2))

   RollNo   Name  Age    City  Marks
3     104  Sneha   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [8]:
print(df['Name'])

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
Name: Name, dtype: object

In [10]:
print(df[['Name','Marks']])

    Name  Marks
0   Amit     85
1  Priya     90
2  Rahul     78
3  Sneha     88
4  Karan     76

In [11]:
df.shape

(5, 5)

In [12]:
print(df[['RollNo','Name','Age','City','Marks']])

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78
3     104  Sneha   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [19]:
print(df.dtypes)

RollNo     int64
Name      object
Age        int64
City      object
Marks      int64
dtype: object

In [22]:
#Display summary statistics

print(df.describe())

           RollNo        Age     Marks
count    5.000000   5.000000   5.00000
mean   103.000000  20.400000  83.40000
std      1.581139   1.140175   6.14817
min    101.000000  19.000000  76.00000
25%    102.000000  20.000000  78.00000
50%    103.000000  20.000000  85.00000
75%    104.000000  21.000000  88.00000
max    105.000000  22.000000  90.00000

In [23]:
print(df.max())

RollNo      105
Name      Sneha
Age          22
City       Pune
Marks        90
dtype: object

In [24]:
print(df.min())

RollNo      101
Name       Amit
Age          19
City      Delhi
Marks        76
dtype: object

In [26]:
print(df["Age"].mean())

20.4

In [28]:
print(df.shape)
print(len(df))

(5, 5)
5

In [29]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RollNo  5 non-null      int64
 1   Name    5 non-null      object
 2   Age     5 non-null      int64
 3   City    5 non-null      object
 4   Marks   5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes
None

In [34]:
#  Task 2

print(df[df["Marks"] > 80])

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
3     104  Sneha   22   Delhi     88

In [36]:
print(df[df["City"]== "Delhi"])

   RollNo   Name  Age   City  Marks
0     101   Amit   20  Delhi     85
3     104  Sneha   22  Delhi     88

In [37]:
print(df[df["Age"]==20])

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
4     105  Karan   20  Jaipur     76

In [46]:
print(df[(df["Marks"]>80)&(df["Marks"]<90)])

   RollNo   Name  Age   City  Marks
0     101   Amit   20  Delhi     85
3     104  Sneha   22  Delhi     88

In [48]:
print(df[(df["City"]=="Delhi") & (df["Marks"]>80)])

   RollNo   Name  Age   City  Marks
0     101   Amit   20  Delhi     85
3     104  Sneha   22  Delhi     88

In [125]:
import pandas as pd

df = pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})
print(df)
df.to_csv("sakshi.csv",index=False)
print("successfully")

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500
successfully

In [32]:
#print(df.loc[0])
#print(df.iloc[0])
#df=[19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23]

In [44]:
df=pd.read_csv("sakshi.csv")
print(df)

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [45]:
#Series

print(df["Marks"])

0     85
1     90
2     78
3     88
4     92
5     76
6     81
7     95
8     89
9     84
10    73
11    77
12    80
13    91
14    87
15    79
16    83
17    86
18    90
19    88
Name: Marks, dtype: int64

In [46]:
#Dataframe

print(df[["Marks","Name"]])

    Marks     Name
0      85    Aarav
1      90   Vivaan
2      78   Aditya
3      88   Vihaan
4      92    Arjun
5      76  Reyansh
6      81  Shaurya
7      95  Krishna
8      89   Ishaan
9      84    Kabir
10     73    Rohan
11     77    Kunal
12     80    Samar
13     91     Yash
14     87      Dev
15     79    Ayaan
16     83    Rudra
17     86       Om
18     90    Aryan
19     88    Parth

In [47]:
print(df.head())

   ID    Name  Age     City  Marks Department  Salary
0   1   Aarav   19  Lucknow     85         CS   30000
1   2  Vivaan   20    Delhi     90         IT   32000
2   3  Aditya   21   Mumbai     78         CS   28000
3   4  Vihaan   22     Pune     88         IT   35000
4   5   Arjun   20   Kanpur     92         EC   40000

In [10]:
print(df.tail())

    Unnamed: 0  ID   Name  Age     City  Marks Department  Salary
15          15  16  Ayaan   21   Jaipur     79         IT   32500
16          16  17  Rudra   22    Delhi     83         EC   38000
17          17  18     Om   20   Mumbai     86         CS   31500
18          18  19  Aryan   21     Pune     90         IT   34500
19          19  20  Parth   23  Lucknow     88         EC   39500

In [17]:
print(df.sample())

   Unnamed: 0  ID     Name  Age   City  Marks Department  Salary
5           5   6  Reyansh   23  Noida     76         CS   27000

In [18]:
print(df.shape)

(20, 8)

In [19]:
print(df.columns)

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'City', 'Marks', 'Department',
       'Salary'],
      dtype='object')

In [48]:
print(df.index)

RangeIndex(start=0, stop=20, step=1)

In [49]:
print(df.dtypes)

ID             int64
Name          object
Age            int64
City          object
Marks          int64
Department    object
Salary         int64
dtype: object

In [56]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   City        20 non-null     object
 4   Marks       20 non-null     int64
 5   Department  20 non-null     object
 6   Salary      20 non-null     int64
dtypes: int64(4), object(3)
memory usage: 1.2+ KB
None

In [59]:
df.describe()

             ID        Age      Marks       Salary
count  20.00000  20.000000  20.000000     20.00000
mean   10.50000  20.950000  84.600000  33725.00000
std     5.91608   1.316894   6.029751   4446.98301
min     1.00000  19.000000  73.000000  27000.00000
25%     5.75000  20.000000  79.750000  30375.00000
50%    10.50000  21.000000  85.500000  32750.00000
75%    15.25000  22.000000  89.250000  36500.00000
max    20.00000  23.000000  95.000000  42000.00000

In [60]:
print(df.loc[0])

ID                  1
Name            Aarav
Age                19
City          Lucknow
Marks              85
Department         CS
Salary          30000
Name: 0, dtype: object

In [61]:
print(df.iloc[6])

ID                  7
Name          Shaurya
Age                21
City             Agra
Marks              81
Department         IT
Salary          33000
Name: 6, dtype: object

In [74]:
df.iloc[:, 1:2]

       Name
0     Aarav
1    Vivaan
2    Aditya
3    Vihaan
4     Arjun
5   Reyansh
6   Shaurya
7   Krishna
8    Ishaan
9     Kabir
10    Rohan
11    Kunal
12    Samar
13     Yash
14      Dev
15    Ayaan
16    Rudra
17       Om
18    Aryan
19    Parth

In [72]:
df.sort_values(by="Marks")

    ID     Name  Age     City  Marks Department  Salary
10  11    Rohan   21     Pune     73         EC   29000
5    6  Reyansh   23    Noida     76         CS   27000
11  12    Kunal   22  Lucknow     77         CS   30000
2    3   Aditya   21   Mumbai     78         CS   28000
15  16    Ayaan   21   Jaipur     79         IT   32500
12  13    Samar   23   Kanpur     80         IT   36000
6    7  Shaurya   21     Agra     81         IT   33000
16  17    Rudra   22    Delhi     83         EC   38000
9   10    Kabir   20   Mumbai     84         IT   34000
0    1    Aarav   19  Lucknow     85         CS   30000
17  18       Om   20   Mumbai     86         CS   31500
14  15      Dev   19     Agra     87         CS   30500
3    4   Vihaan   22     Pune     88         IT   35000
19  20    Parth   23  Lucknow     88         EC   39500
8    9   Ishaan   19    Delhi     89         CS   31000
1    2   Vivaan   20    Delhi     90         IT   32000
18  19    Aryan   21     Pune     90         IT   34500
13  14     Yash   20    Noida     91         EC   41000
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000

In [73]:
df.sort_index()

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [77]:
# Missing data

#isnull()

df.isnull()
df.isnull().sum()

ID            0
Name          0
Age           0
City          0
Marks         0
Department    0
Salary        0
dtype: int64

In [76]:
df.notnull()

      ID  Name   Age  City  Marks  Department  Salary
0   True  True  True  True   True        True    True
1   True  True  True  True   True        True    True
2   True  True  True  True   True        True    True
3   True  True  True  True   True        True    True
4   True  True  True  True   True        True    True
5   True  True  True  True   True        True    True
6   True  True  True  True   True        True    True
7   True  True  True  True   True        True    True
8   True  True  True  True   True        True    True
9   True  True  True  True   True        True    True
10  True  True  True  True   True        True    True
11  True  True  True  True   True        True    True
12  True  True  True  True   True        True    True
13  True  True  True  True   True        True    True
14  True  True  True  True   True        True    True
15  True  True  True  True   True        True    True
16  True  True  True  True   True        True    True
17  True  True  True  True   True        True    True
18  True  True  True  True   True        True    True
19  True  True  True  True   True        True    True

In [129]:
df[df["Marks"]>85]

    ID     Name  Age     City  Marks Department  Salary
1    2   Vivaan   20    Delhi     90         IT   32000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [130]:
df[df["Age"]==20]

    ID    Name  Age    City  Marks Department  Salary
1    2  Vivaan   20   Delhi     90         IT   32000
4    5   Arjun   20  Kanpur     92         EC   40000
9   10   Kabir   20  Mumbai     84         IT   34000
13  14    Yash   20   Noida     91         EC   41000
17  18      Om   20  Mumbai     86         CS   31500

In [131]:
df[df["City"]=="Delhi"]

    ID    Name  Age   City  Marks Department  Salary
1    2  Vivaan   20  Delhi     90         IT   32000
8    9  Ishaan   19  Delhi     89         CS   31000
16  17   Rudra   22  Delhi     83         EC   38000

In [132]:
df[df["City"]=="Mumbai"]

    ID    Name  Age    City  Marks Department  Salary
2    3  Aditya   21  Mumbai     78         CS   28000
9   10   Kabir   20  Mumbai     84         IT   34000
17  18      Om   20  Mumbai     86         CS   31500

In [134]:
df[df["Salary"]>35000]

    ID     Name  Age     City  Marks Department  Salary
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [135]:
df[df["Marks"]<80]

    ID     Name  Age     City  Marks Department  Salary
2    3   Aditya   21   Mumbai     78         CS   28000
5    6  Reyansh   23    Noida     76         CS   27000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
15  16    Ayaan   21   Jaipur     79         IT   32500

In [136]:
df[df["Age"]>21]

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [137]:
df[df["Department"]=="CS"]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
2    3   Aditya   21   Mumbai     78         CS   28000
5    6  Reyansh   23    Noida     76         CS   27000
8    9   Ishaan   19    Delhi     89         CS   31000
11  12    Kunal   22  Lucknow     77         CS   30000
14  15      Dev   19     Agra     87         CS   30500
17  18       Om   20   Mumbai     86         CS   31500

In [138]:
df[df["Department"]=="IT"]

    ID     Name  Age    City  Marks Department  Salary
1    2   Vivaan   20   Delhi     90         IT   32000
3    4   Vihaan   22    Pune     88         IT   35000
6    7  Shaurya   21    Agra     81         IT   33000
9   10    Kabir   20  Mumbai     84         IT   34000
12  13    Samar   23  Kanpur     80         IT   36000
15  16    Ayaan   21  Jaipur     79         IT   32500
18  19    Aryan   21    Pune     90         IT   34500

In [139]:
df[df["City"]=="Lucknow"]

    ID   Name  Age     City  Marks Department  Salary
0    1  Aarav   19  Lucknow     85         CS   30000
11  12  Kunal   22  Lucknow     77         CS   30000
19  20  Parth   23  Lucknow     88         EC   39500

In [144]:
#medium level

df[(df["Marks"]>80)&(df["Age"]<21)]

    ID    Name  Age     City  Marks Department  Salary
0    1   Aarav   19  Lucknow     85         CS   30000
1    2  Vivaan   20    Delhi     90         IT   32000
4    5   Arjun   20   Kanpur     92         EC   40000
8    9  Ishaan   19    Delhi     89         CS   31000
9   10   Kabir   20   Mumbai     84         IT   34000
13  14    Yash   20    Noida     91         EC   41000
14  15     Dev   19     Agra     87         CS   30500
17  18      Om   20   Mumbai     86         CS   31500

In [147]:
df[(df["City"]=="Delhi")&(df["Marks"]>85)]

   ID    Name  Age   City  Marks Department  Salary
1   2  Vivaan   20  Delhi     90         IT   32000
8   9  Ishaan   19  Delhi     89         CS   31000

In [151]:
df[(df["City"]=="Mumbai")|(df["City"]=="Pune")]

    ID    Name  Age    City  Marks Department  Salary
2    3  Aditya   21  Mumbai     78         CS   28000
3    4  Vihaan   22    Pune     88         IT   35000
9   10   Kabir   20  Mumbai     84         IT   34000
10  11   Rohan   21    Pune     73         EC   29000
17  18      Om   20  Mumbai     86         CS   31500
18  19   Aryan   21    Pune     90         IT   34500

In [155]:
df[df["City"]!="Lucknow"]

    ID     Name  Age    City  Marks Department  Salary
1    2   Vivaan   20   Delhi     90         IT   32000
2    3   Aditya   21  Mumbai     78         CS   28000
3    4   Vihaan   22    Pune     88         IT   35000
4    5    Arjun   20  Kanpur     92         EC   40000
5    6  Reyansh   23   Noida     76         CS   27000
6    7  Shaurya   21    Agra     81         IT   33000
7    8  Krishna   22  Jaipur     95         EC   42000
8    9   Ishaan   19   Delhi     89         CS   31000
9   10    Kabir   20  Mumbai     84         IT   34000
10  11    Rohan   21    Pune     73         EC   29000
12  13    Samar   23  Kanpur     80         IT   36000
13  14     Yash   20   Noida     91         EC   41000
14  15      Dev   19    Agra     87         CS   30500
15  16    Ayaan   21  Jaipur     79         IT   32500
16  17    Rudra   22   Delhi     83         EC   38000
17  18       Om   20  Mumbai     86         CS   31500
18  19    Aryan   21    Pune     90         IT   34500

In [157]:
df[(df["Marks"]>80)&(df["Marks"]<90)]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
3    4   Vihaan   22     Pune     88         IT   35000
6    7  Shaurya   21     Agra     81         IT   33000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
14  15      Dev   19     Agra     87         CS   30500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
19  20    Parth   23  Lucknow     88         EC   39500

In [158]:
df[(df["Department"]=="CS")|(df["Department"]=="EC")]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
2    3   Aditya   21   Mumbai     78         CS   28000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
19  20    Parth   23  Lucknow     88         EC   39500

In [159]:
df[(df["Salary"]>32000)&(df["Department"]=="IT")]

    ID     Name  Age    City  Marks Department  Salary
3    4   Vihaan   22    Pune     88         IT   35000
6    7  Shaurya   21    Agra     81         IT   33000
9   10    Kabir   20  Mumbai     84         IT   34000
12  13    Samar   23  Kanpur     80         IT   36000
15  16    Ayaan   21  Jaipur     79         IT   32500
18  19    Aryan   21    Pune     90         IT   34500

In [161]:
df[(df["Age"]==21)|(df["Marks"]>90)]

    ID     Name  Age    City  Marks Department  Salary
2    3   Aditya   21  Mumbai     78         CS   28000
4    5    Arjun   20  Kanpur     92         EC   40000
6    7  Shaurya   21    Agra     81         IT   33000
7    8  Krishna   22  Jaipur     95         EC   42000
10  11    Rohan   21    Pune     73         EC   29000
13  14     Yash   20   Noida     91         EC   41000
15  16    Ayaan   21  Jaipur     79         IT   32500
18  19    Aryan   21    Pune     90         IT   34500

In [164]:
df[(df["City"]=="Delhi")|(df["City"]=="Mumbai")|(df["City"]=="Lucknow")]

    ID    Name  Age     City  Marks Department  Salary
0    1   Aarav   19  Lucknow     85         CS   30000
1    2  Vivaan   20    Delhi     90         IT   32000
2    3  Aditya   21   Mumbai     78         CS   28000
8    9  Ishaan   19    Delhi     89         CS   31000
9   10   Kabir   20   Mumbai     84         IT   34000
11  12   Kunal   22  Lucknow     77         CS   30000
16  17   Rudra   22    Delhi     83         EC   38000
17  18      Om   20   Mumbai     86         CS   31500
19  20   Parth   23  Lucknow     88         EC   39500

In [165]:
df[(df["Marks"]>85)&(df["Age"]>=20)]

    ID     Name  Age     City  Marks Department  Salary
1    2   Vivaan   20    Delhi     90         IT   32000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
13  14     Yash   20    Noida     91         EC   41000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [113]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya",None,"Karan","Priya","Rahul","Neha",None,
             "Vikas","Pooja","Ankit","Simran","Rohit",None,"Kajal",
             "Deepak","Meena","Arjun","Nisha",None],

    "Age": [20,21,np.nan,22,19,23,21,20,np.nan,22,
            24,23,21,20,22,np.nan,19,21,23,20],

    "City": ["Delhi","Mumbai","Pune",None,"Jaipur","Delhi","Mumbai",
             "Pune","Delhi",None,"Jaipur","Mumbai","Delhi","Pune",
             None,"Delhi","Mumbai","Jaipur","Pune","Delhi"],

    "Marks": [85,90,78,np.nan,88,76,91,82,95,np.nan,
              80,84,79,92,87,75,np.nan,89,81,93]
})

print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [80]:
df.isnull().sum()

Student_ID    0
Name          4
Age           3
City          3
Marks         3
dtype: int64

In [82]:
df.notnull().sum()

Student_ID    20
Name          16
Age           17
City          17
Marks         17
dtype: int64

In [83]:
df.dropna()

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [92]:
# to remove frrom data frame permanently

df.dropna(inplace=True)
print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [95]:
# to fill missing values
df.fillna(0)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103       0   0.0    Pune   78.0
3          104   Karan  22.0       0    0.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108       0  20.0    Pune   82.0
8          109   Vikas   0.0   Delhi   95.0
9          110   Pooja  22.0       0    0.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114       0  20.0    Pune   92.0
14         115   Kajal  22.0       0   87.0
15         116  Deepak   0.0   Delhi   75.0
16         117   Meena  19.0  Mumbai    0.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120       0  20.0   Delhi   93.0

In [98]:
df.fillna("Not available")

    Student_ID           Name            Age           City          Marks
0          101           Aman           20.0          Delhi           85.0
1          102           Riya           21.0         Mumbai           90.0
2          103  Not available  Not available           Pune           78.0
3          104          Karan           22.0  Not available  Not available
4          105          Priya           19.0         Jaipur           88.0
5          106          Rahul           23.0          Delhi           76.0
6          107           Neha           21.0         Mumbai           91.0
7          108  Not available           20.0           Pune           82.0
8          109          Vikas  Not available          Delhi           95.0
9          110          Pooja           22.0  Not available  Not available
10         111          Ankit           24.0         Jaipur           80.0
11         112         Simran           23.0         Mumbai           84.0
12         113          Rohit           21.0          Delhi           79.0
13         114  Not available           20.0           Pune           92.0
14         115          Kajal           22.0  Not available           87.0
15         116         Deepak  Not available          Delhi           75.0
16         117          Meena           19.0         Mumbai  Not available
17         118          Arjun           21.0         Jaipur           89.0
18         119          Nisha           23.0           Pune           81.0
19         120  Not available           20.0          Delhi           93.0

In [101]:
#df.fillna(df["Name"]=="None")
df.fillna({'Name': 'Not Available', 'Marks' : 0, 'Age' : 18})

    Student_ID           Name   Age    City  Marks
0          101           Aman  20.0   Delhi   85.0
1          102           Riya  21.0  Mumbai   90.0
2          103  Not Available  18.0    Pune   78.0
3          104          Karan  22.0    None    0.0
4          105          Priya  19.0  Jaipur   88.0
5          106          Rahul  23.0   Delhi   76.0
6          107           Neha  21.0  Mumbai   91.0
7          108  Not Available  20.0    Pune   82.0
8          109          Vikas  18.0   Delhi   95.0
9          110          Pooja  22.0    None    0.0
10         111          Ankit  24.0  Jaipur   80.0
11         112         Simran  23.0  Mumbai   84.0
12         113          Rohit  21.0   Delhi   79.0
13         114  Not Available  20.0    Pune   92.0
14         115          Kajal  22.0    None   87.0
15         116         Deepak  18.0   Delhi   75.0
16         117          Meena  19.0  Mumbai    0.0
17         118          Arjun  21.0  Jaipur   89.0
18         119          Nisha  23.0    Pune   81.0
19         120  Not Available  20.0   Delhi   93.0

In [108]:
#df["Marks"].mean()

df["Marks"] = df["Marks"].replace(0, np.nan)


df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None   85.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None   85.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai   85.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [111]:
df.replace("Riya","Sakshi")

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102  Sakshi  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None   85.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None   85.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai   85.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0